server:
  ssl:
    enabled: false

spring:
  datasource:
    url: jdbc:h2:file:/data/metadata;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

vault-sync:
  storage-path: /data/files

logging:
  level:
    root: INFO
    com.vaultsync: INFO
