# /etc/fail2ban/jail.d/vault-sync-edge.conf
[vault-sync-edge]
enabled  = true
port     = http,https
filter   = vault-sync-edge
logpath  = /root/vault-sync/deploy/nginx/log/access.log
maxretry = 3
findtime = 10m
bantime  = 1h
